//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG1180_NBD_APP.Daily_Work_Reports {
    
    
    public partial class DesignerDailyWorkReports {
    }
}
